### ISSUE TITLE
[3.2] Adding user without roles displays no validation errors

### ISSUE THREAD

**Issue by stevebauman** [orchestral/foundation#204]
Since the input name for roles is `roles[]` and the validation error is returned for the input key `roles`, no validation error is displayed. This occurs in `v3.1.*` as well.

**Comment by crynobone** [comment]
Should be fixed in the upcoming patch releases.

https://github.com/orchestral/foundation/commit/c56a5355ff0c045771bb09b1a9a11ac1b6f99293

**Comment by stevebauman** [comment]
Awesome thanks!
