### ISSUE TITLE
[3.2] Encryption for Orchestra Settings

### ISSUE THREAD

**Issue by stevebauman** [orchestral/foundation#206]
Isn't it a possibly a security issue if the database get's compromised that the email server password is stored in plain text? Shouldn't it be encrypted and then decrypted when needed?

https://github.com/orchestral/foundation/blob/master/src/Processor/Setting.php#L120

**Comment by crynobone** [comment]
This should be available on latest code. Will tag soon since it updated on branch 3.0, 3.1 and 3.2 and involved support, memory, notifier and foundation components.

**Comment by crynobone** [comment]
Done

**Comment by stevebauman** [comment]
Awesome thanks for the quick response on this!
