### ISSUE TITLE
Add reauthenticate support for Orchestra Platform

### ISSUE THREAD

**Issue by crynobone** [orchestral/foundation#211]
Refer to https://github.com/mpociot/reauthenticate

**Comment by crynobone** [comment]
Done with temporary solution, will revisit `mpociot/reauthenticate` once issue regarding dependencies and both mpociot/reauthenticate#14 and mpociot/reauthenticate#15 merged.

**Comment by mpociot** [comment]
Your pull requests are merged. Thanks again

**Comment by crynobone** [comment]
@mpociot welcome, working on readding the package right now, but somehow packagist doesn't seem to get the update https://packagist.org/packages/mpociot/reauthenticate

**Comment by mpociot** [comment]
It's now on packagist too. Auto update wasn't setup for this repo

**Comment by crynobone** [comment]
Awesome.
