### ISSUE TITLE
str_limit function not exist

### ISSUE THREAD

**Issue by parse-dinghua** [orchestral/foundation#220]
![image](https://user-images.githubusercontent.com/54979620/66539197-d0d8da00-eb59-11e9-8f97-8229e3e4955e.png)

**Comment by crynobone** [comment]
@parse-dinghua can you submit a PR for this, in the meantimes you could consider adding `composer require "laravel/helpers"` to your project.

**Comment by crynobone** [comment]
Just tagged a fix since I have some free time.
