### ISSUE TITLE
Stuck on installation

### ISSUE THREAD

**Issue by parse-dinghua** [orchestral/foundation#221]
- Package Version: 4.2.0
- Laravel Version: 6.x.dev
- PHP Version: 7.3.12

### Description:
Can not complete install setup.

### Steps To Reproduce:
1. install follow documentation
2. open http://locahost/admin and install
3. See success page and click login
4. Redirect to  http://locahost/admin/install page

I checked the database, and see users record but orchestra_options table is empty.

Look around the source code, I guess the memory instance lead this issue.
If application is not installed,  a new memory instance with driver `runtime.orchestra` will be created, which do not insert data to database after install.

**Comment by crynobone** [comment]
Can you try the bugfix @parse-dinghua
