### ISSUE TITLE
using Illuminate\Foundation\Bus\DispatchesJobs in Job extend from Orchestra\Foundation\Jobs\Job 

### ISSUE THREAD

**Issue by dickylhf** [orchestral/foundation#222]
I have just updated my application from Foundation 4.1.0 to 4.2.0, and after the upgrade, I got the following error during running Job.

PHP Fatal error:  Cannot make static method Orchestra\Foundation\Jobs\Job::dispatch() non static in class Illuminate\Foundation\Bus\DispatchesJobs in /var/www/vhosts/www/vendor/yyy/zzz/src/Jobs/InitSetup.php on line 13

   Symfony\Component\Debug\Exception\FatalErrorException  : Cannot make static method Orchestra\Foundation\Jobs\Job::dispatch() non static in class Illuminate\Foundation\Bus\DispatchesJobs

  at /var/www/vhosts/www/vendor/yyy/zzz/src/Jobs/InitSetup.php:13
     9| use XXX\Core\Jobs\UpdateCache;
    10| use Illuminate\Foundation\Bus\DispatchesJobs;
    11| use Orchestra\Foundation\Jobs\Job;
    12|
  > 13| class InitSetup extends Job
    14| {
    15| 	use DispatchesJobs;
    16|
    17|     public function __construct()

   Whoops\Exception\ErrorException  : Cannot make static method Orchestra\Foundation\Jobs\Job::dispatch() non static in class Illuminate\Foundation\Bus\DispatchesJobs

  at /var/www/vhosts/www/vendor/yyy/zzz/src/Jobs/InitSetup.php:13
     9| use XXX\Core\Jobs\UpdateCache;
    10| use Illuminate\Foundation\Bus\DispatchesJobs;
    11| use Orchestra\Foundation\Jobs\Job;
    12|
  > 13| class InitSetup extends Job
    14| {
    15| 	use DispatchesJobs;
    16|
    17|     public function __construct()

  Exception trace:

  1   Whoops\Run::handleError("Cannot make static method Orchestra\Foundation\Jobs\Job::dispatch() non static in class Illuminate\Foundation\Bus\DispatchesJobs", "/var/www/vhosts/www/vendor/yyy/zzz/src/Jobs/InitSetup.php")
      /var/www/vhosts/www/vendor/filp/whoops/src/Whoops/Run.php:408

  2   Whoops\Run::handleShutdown()
      [internal]:0

And this is my job structure

`namespace XXX\YYY\Jobs;

use XXX\Core\Jobs\UpdateCache;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Orchestra\Foundation\Jobs\Job;

class InitSetup extends Job
{
	use DispatchesJobs;
	
    public function __construct()
    {
    }

    public function handle()
    {
        $this->dispatch(new UpdateCache());
    }
}`

I think the main reason is I used Illuminate\Foundation\Bus\DispatchesJobs in my job and I extended Orchestra\Foundation\Jobs\Job. But on v.4.2.0, Orchestra\Foundation\Jobs\Job used Illuminate\Foundation\Bus\Dispatchable by default and the function name dispatch / dispatchNow id crashed.

Just wonder if there are suggestion / workaround that I don't need to change my code since I used this approach in so many Jobs. And I can't upgrade to 4.2.0 due to this issue. 

Thanks a lot!!

**Comment by crynobone** [comment]
You should use your own `Job` file. I have that base class so that all foundation jobs can extends that.

**Comment by dickylhf** [comment]
Thanks for advise. I will do that in order to solve my problem. Just one more question, after I upgrade to 4.2.0, why my laravel upgrade from v6.9.0 to .x-dev f3c1f48 ? 

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 6 updates, 1 removal
  - Removing erusev/parsedown (1.7.4)
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing league/commonmark (1.1.2): Loading from cache
  - Installing league/commonmark-ext-table (v2.1.0): Loading from cache
  - Removing laravel/framework (v6.9.0)
  - Installing laravel/framework (6.x-dev f3c1f48): Loading from cache
  - Updating orchestra/foundation (v4.1.0 => v4.2.0): Loading from cache

**Comment by crynobone** [comment]
Yes because 4.2.0 requires `laravel/framework=^6.10` which should release by end of today

**Comment by dickylhf** [comment]
Cool. Thanks a lot. 
Then I will try to update again to see if it will use laravel 6.10 or not.
